version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expenses-app
    volumes:
      - .:/var/www
    networks:
      - laravel
    ports:
      - "9000:9000"  # PHP-FPM
      - "5173:5173"  # Vite
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: expenses-web
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: expenses-db
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
